### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mulle-nat** [dblommesteijn/autotools-example#1]
Was looking for an autotool example to test something, followed the instructions... 

```
autoreconf -vfi
./configure
make
```

It didn't work. Fairly typical for autoconf projects IMO :)

```
toollib/print.cpp:1:10: fatal error: 'toollib.h' file not found
#include <toollib.h>
         ^
1 error generated.
```

**Comment by dblommesteijn** [comment]
@mulle-nat Looks like your platform is missing the required header files to compile with.

**Comment by mulle-nat** [comment]
Hardly. It's in your project. [toollib.h](https://github.com/dblommesteijn/autotools-example/blob/master/include/toollib.h). If it wasn't, isn't that exactly what `autoconf` is for ? To check ahead of compilation ? :)

**Comment by dblommesteijn** [comment]
Well yes actually it is, did you run sudo make install in the project root?

**Comment by mulle-nat** [comment]
I did what I wrote in the first comment.
How is `sudo make install` gonna work, if `make` already fails ?

**Comment by dblommesteijn** [comment]
Maybe you should tell me what you're trying, as a statement like: doesn't work is not really helpful.

**Comment by mulle-nat** [comment]
What exactly is unclear and non-reproducable about the original text ?

#### Here I am explaining to you what I am trying to do, with steps to reproduce

> Was looking for an autotool example to test something, followed the instructions...
> 
> ```
> autoreconf -vfi
> ./configure
> make
> ```

#### Here I am explaining what the error is I am getting

> 
> It didn't work. Fairly typical for autoconf projects IMO :)
>
> ```
> toollib/print.cpp:1:10: fatal error: 'toollib.h' file not found
> #include <toollib.h>
>        ^
>  1 error generated.

**Comment by dblommesteijn** [comment]
Well sorry but, you're stating it yourself: `fairly typical for autoconf projects`, maybe you should do some more research about it before you start asking questions.
